export const GET_INVENTORY_START='GET_INVENTORY_START';
export const GET_INVENTORY_SUCCESS='GET_INVENTORY_SUCCESS';
export const GET_INVENTORY_FAIL='GET_INVENTORY_FAIL';

export const ADD_NEWBEER ='ADD_NEWBEER';
export const UPDATE_BEER='UPDATE_BEER';
export const DELETE_BEER='DELETE_BEER';


export const ADD_BEER='UPDATE_BEER';
export const REMOVE_BEER='REMOVE_BEER';
export const REMOVE_FROM_CART='REMOVE_FROM_CART';
export const CANCEL_CHECKOUT='CANCEL_CHECKOUT';
export const CHECKOUT='CHECKOUT'

export const POST_ORDER_START='POST_ORDER_START'
export const POST_ORDER_SUCCESS='POST_ORDER_SUCCESS'
export const POST_ORDER_FAIL='POST_ORDER_FAIL'





