export const GET_INVENTORY_START='GET_INVENTORY_START';
export const GET_INVENTORY_SUCCESS='GET_INVENTORY_SUCCESS';
export const GET_INVENTORY_FAIL='GET_INVENTORY_FAIL';

export const ADD_NEWBEER ='ADD_NEWBEER';
export const UPDATE_BEER='UPDATE_BEER';
export const DELETE_BEER='DELETE_BEER';


export const ADD_BEER='UPDATE_BEER';
export const REMOVE_BEER='REMOVE_BEER';
export const REMOVE_FROM_CART='REMOVE_FROM_CART';
export const CANCEL_CHECKOUT='CANCEL_CHECKOUT';
export const CHECKOUT='CHECKOUT'

export const POST_ORDER_START='POST_ORDER_START';
export const POST_ORDER_SUCCESS='POST_ORDER_SUCCESS';
export const POST_ORDER_FAIL='POST_ORDER_FAIL';


export const AUTH_START='AUTH_START';
export const AUTH_SUCCESS='AUTH_SUCCESS';
export const AUTH_FAIL='AUTH_FAIL';
export const LOGOUT_SUCCESS='LOGOUT_SUCCESS';
export const LOGOUT_FAIL='LOGOUT_FAIL';
export const SET_REDIRECT_PATH='SET_REDIRECT_PATH';
export const DELETE_ERROR_REOPRT='DELETE_ERROR_REOPRT';








